services:

  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/usr/share/nginx/html

  apache:
    image: httpd:latest
    container_name: apache-server
    ports:
      - "8081:80"
    volumes:
      - ./apache:/usr/local/apache2/htdocs/

  mysql:
    image: mysql:8.0
    container_name: mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: